export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";



export const SHIPPING_DETAILS_REQUEST = "SHIPPING_DETAILS_REQUEST";
export const SHIPPING_DETAILS_SUCCESS = "SHIPPING_DETAILS_SUCCESS";
export const SHIPPING_DETAILS_FAIL = "SHIPPING_DETAILS_FAIL";

export const SHIPPING_DETAILS = "SHIPPING_DETAILS"

export const PAYMENT_METHOD = "PAYMENT_METHOD";
